# Generated by Django 6.0.5 on 2026-05-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('promos', 'Promos Grupales'), ('desayunos', 'Desayunos'), ('almuerzos', 'Almuerzos'), ('cenas', 'Cenas'), ('bocaditos', 'Bocaditos')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('badge', models.CharField(blank=True, choices=[('HOT', 'Hot'), ('NEW', 'New')], max_length=10, null=True)),
            ],
        ),
    ]
